<template>
  <v-chart class="chart" :option="option" autoresize />
</template>
<script>
import VChart, { THEME_KEY } from "vue-echarts";
import { ref, defineComponent } from "vue";
import "echarts";

export default defineComponent({
  name: "HelloWorld",
  components: { VChart },
  provide: { [THEME_KEY]: "light" },
  setup() {
    const data = [
      22,
              62,
              91,
              51,
              91,
              94,
              56,
              77,
              51,
              99,
              2,
              63,
              60,
              62,
              73,
              82,
              53,
              75,
              65,
              80,
              59,
              69,
              2,
              53,
              69,
              78,
              55,
              54,
              65,
              53,
              51,
              41,
              81,
              68,
              100,
              34,
              56,
              82,
              63,
              56,
              66,
              82,
              76,
              90,
              93,
              82,
              56,
              34,
              43,
              21,
              57,
              42,
              2,
              62,
              56,
              60,
              69,
              62,
              72,
              39,
              21,
              100,
              67,
              83,
              32,
              52,
              73,
              73,
              97,
              52,
              59,
              36,
              94,
              69,
              59,
              30,
              50,
            
          ];
    const option = ref({
      tooltip: {
        function(parms) {
          return parms[0];
        },
      },
      dataZoom: [{  type: 'slider',
                    startValue: 20,
                    endValue: 65,
                    showDataShadow: false,
                    bottom: 10,
                    height: 12,
                    borderColor: 'transparent',
                    backgroundColor: 'transparent',
                    fillerColor: '#b3b3b3',
                    handleStyle: {
                      color: '#b3b3b3',
                      borderColor: 'transparent',
                      borderWidth: 0
                    },
                    dataBackground: {
                      areaStyle: {
                        color: '#e2e2e2'
                      },
                      lineStyle: {
                        opacity: 0
                      }
                    }
                  }],
      grid: { bottom: 180 },
      xAxis: {
        type: "category",
        axisTick: { show: false },
        axisLabel: {
          show: true,
          rotate: 90,
          fontSize: 13,
        },
        data: [
          "Over Speed",
            "Mobile Use",
            "Sudden Braking",
            "Pedestrian Crossing",
            "Sudden Braking",
            "Sudden Braking",
            "Sudden Braking",
            "Pedestrian Crossing",
            "School",
            "Force Acceleration",
            "School",
            "Sudden Braking",
            "Pedestrian Crossing",
            "Sudden Braking",
            "Sudden Braking",
            "Sudden Braking",
            "Pedestrian Crossing",
            "Pedestrian Crossing",
            "School",
            "Sudden Braking",
            "Caution",
            "Caution",
            "Over Speed",
            "Pedestrian Crossing",
            "Pedestrian Crossing",
            "Sudden Braking",
            "School",
            "Pedestrian Crossing",
            "Intersection",
            "Intersection",
            "Curve",
            "Over Speed",
            "Intersection",
            "Curve",
            "Over Speed",
            "Sudden Braking",
            "Sudden Braking",
            "Sudden Braking",
            "Sudden Braking",
            "Curve",
            "Curve",
            "Over Speed",
            "Curve", 
            "Sudden Braking",
            "Curve",
            "Sudden Braking",
            "Curve",
            "Sudden Braking",
            "Sudden Braking",
            "Over Speed",
            "Curve",
            "Over Speed",
            "Over Speed",
            "Curve",
            "Over Speed",
            "Curve",
            "Sudden Braking",
            "Curve",
            "Sudden Braking",
            "Over Speed",
            "Over Speed",
            "Curve",
            "Curve",
            "Sudden Braking",
            "Over Speed",
            "Over Speed",
            "Curve",
            "Curve",
            "Over Speed",
            "Curve",
            "Over Speed",
            "Curve",
            "Sudden Braking",
            "Sudden Braking",
            "Curve",
            "Curve",
            "Pedestrian Crossing",
          
        ],
      },
      yAxis: {
        type: "value",
        min: 0,
        max: 100,
        interval: 10,
        splitLine: {
          lineStyle: {
            color: [
              "#827f7f", // default split line color 10
              "#e2e3e1", // default split line color 20
              "#e2e3e1", // default split line color 30
              "#e2e3e1", // default split line color 40
              "#e2e3e1", // darker split line color at 50
              "#e2e3e1", // default split line color 60
              "#827f7f", // darker split line color at 70
              "#e2e3e1", // darker split line color at 80
              "#e2e3e1", // darker split line color at 90
              "#827f7f", // darker split line color at 100
            ],
            opacity: 1, // set opacity to 1 to make the colors fully visible
            type: "dashed",
          },
        },
      },
      visualMap: {
        // show: false,
        top: 85,
        right: 5,
        seriesIndex: 0,
        pieces: [
          {
            gte: 0,
            lte: 60,
            color: "#0255d1",
            label:  "0-60 →   " + data.filter(value => value > -1 && value <= 60).length 
          },
          {
            gt: 60,
            lte: 90,
            color: "#ffbf00",
            label:  "60-90 →   " + data.filter(value => value > 60 && value <= 90).length
          },
          {
            gt: 90,
            lte: 100,
            color: "#FD0100",
            label:  "90-100 →   " + data.filter(value => value > 90 && value <= 100).length
          },
        ],
        outOfRange: {
          color: "#999",
        },
      },
      title: {
       text: "COUNT",
       textStyle: {
       fontSize: 14,
       fontWeight: "bold",
       color: "#403e3a",
      },
    top: 55,
    right: 18,
  },
      series: [
        {
          type: "scatter",
          data: [
            22,
              62,
              91,
              51,
              91,
              94,
              56,
              77,
              51,
              99,
              2,
              63,
              60,
              62,
              73,
              82,
              53,
              75,
              65,
              80,
              59,
              69,
              2,
              53,
              69,
              78,
              55,
              54,
              65,
              53,
              51,
              41,
              81,
              68,
              100,
              34,
              56,
              82,
              63,
              56,
              66,
              82,
              76,
              90,
              93,
              82,
              56,
              34,
              43,
              21,
              57,
              42,
              2,
              62,
              56,
              60,
              69,
              62,
              72,
              39,
              21,
              100,
              67,
              83,
              32,
              52,
              73,
              73,
              97,
              52,
              59,
              36,
              94,
              69,
              59,
              30,
              50, 
            
          ],
          itemStyle: {
            color: "#f08080",
            borderColor: "#6e706f",
            borderWidth: 0.7,
          },
        },
        {
          type: "bar",
          barWidth: 1,
          data: [
            22,
              62,
              91,
              51,
              91,
              94,
              56,
              77,
              51,
              99,
              2,
              63,
              60,
              62,
              73,
              82,
              53,
              75,
              65,
              80,
              59,
              69,
              2,
              53,
              69,
              78,
              55,
              54,
              65,
              53,
              51,
              41,
              81,
              68,
              100,
              34,
              56,
              82,
              63,
              56,
              66,
              82,
              76,
              90,
              93,
              82,
              56,
              34,
              43,
              21,
              57,
              42,
              2,
              62,
              56,
              60,
              69,
              62,
              72,
              39,
              21,
              100,
              67,
              83,
              32,
              52,
              73,
              73,
              97,
              52,
              59,
              36,
              94,
              69,
              59,
              30,
              50, 
            
          ],
          itemStyle: {
            color: "#c7c1c1",
          },
        },
      ],
      markLine: {
        data: [
          {
            yAxis: 90,
            lineStyle: {
              color: "#00040a",
              type: "dashed",
            },
            label: {
              formatter: "Threshold: {c}",
            },
          },
        ],
      },
    });
    return { option };
  },
});
</script>

<style scoped>
.chart {
  height: 100vh;
}
</style>

